name: Bug Report
description: File a report to help us reproduce and correct the bug.
labels: ['bug']

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue has not been
      addressed by searching through [the past issues](https://github.com/modalic/python-sdk/issues).
- type: textarea
  attributes:
    label: Describe the bug
    description: >
      A clear and concise description of what the bug is.
  validations:
    required: true

- type: markdown
  attributes:
    value: >
      Thanks for the contribution!
