name: "Setup virtual environment using Poetry"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2.1.6
      with:
        path: |
          .venv
          poetry.lock
        # Cache the complete venv dir for a given os, python version and pyproject.toml
        key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}-py-${{ matrix.python-version }}

    - name: Install Project
      shell: bash
      # if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install
