name: Build & Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.0
      - name: Install build tools
        run: |
          python -m pip install -U pip==22.0.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip -r requirements.txt
          python -m pip install torch
          python -m pip install tensorflow

      - name: Build and deploy docs
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: chmod +x scripts/generate-docs.sh && bash scripts/generate-docs.sh
